import {
  Baby,
  Users,
  User,
  Laugh,
  Heart,
  Sparkles,
  Star,
  Zap,
  Trophy,
  Briefcase,
  GraduationCap,
  Heart as HeartIcon,
  Plane,
  Lightbulb,
  BookOpen,
  Coffee,
  MessageCircle,
  BookOpen as BookOpenIcon,
  Building2,
  GraduationCap as GraduationCapIcon,
  Globe,
  Smartphone,
  Laptop,
  Building,
  Video,
  ThumbsDown,
  Frown,
  Smile,
  ThumbsUp,
  Award,
  AlertCircle,
  XCircle,
  Flame,
  Battery,
  BatteryMedium,
  BatteryCharging,
} from "lucide-react";

export const questions = [
  {
    id: "age_range",
    title: "ما هي الفئة العمرية الخاصة بك؟",
    options: [
      { value: "18-24", label: "18-24", icon: <Baby className="h-5 w-5" /> },
      { value: "25-34", label: "25-34", icon: <Users className="h-5 w-5" /> },
      { value: "35-44", label: "35-44", icon: <User className="h-5 w-5" /> },
      { value: "45-54", label: "45-54", icon: <Laugh className="h-5 w-5" /> },
      { value: "55+", label: "55+", icon: <Heart className="h-5 w-5" /> },
    ],
    type: "single",
  },
  {
    id: "hebrew_level",
    title: "ما هو مستواك الحالي في اللغة العبرية؟",
    options: [
      {
        value: "beginner",
        label: "مبتدئ",
        description: "لا أعرف أي كلمات أو القليل جداً منها",
        icon: <Sparkles className="h-6 w-6 text-blue-400" />,
      },
      {
        value: "elementary",
        label: "أساسي",
        description: "أعرف بعض الكلمات والعبارات البسيطة",
        icon: <Star className="h-6 w-6 text-yellow-400" />,
      },
      {
        value: "intermediate",
        label: "متوسط",
        description: "يمكنني إجراء محادثات بسيطة",
        icon: <Zap className="h-6 w-6 text-orange-400" />,
      },
      {
        value: "advanced",
        label: "متقدم",
        description: "أتحدث بطلاقة نسبياً ولكن أواجه بعض التحديات",
        icon: <Trophy className="h-6 w-6 text-green-500" />,
      },
    ],
    type: "single",
  },
  {
    id: "motivation",
    title: "ما هو الدافع الرئيسي لتعلم اللغة العبرية؟",
    options: [
      {
        value: "work",
        label: "العمل",
        description: "أحتاج العبرية للتواصل في مكان العمل",
        icon: <Briefcase className="h-6 w-6 text-blue-500" />,
      },
      {
        value: "study",
        label: "الدراسة",
        description: "أحتاج العبرية للدراسة أو البحث الأكاديمي",
        icon: <GraduationCap className="h-6 w-6 text-purple-500" />,
      },
      {
        value: "family",
        label: "العائلة",
        description: "لدي أفراد عائلة يتحدثون العبرية",
        icon: <HeartIcon className="h-6 w-6 text-red-500" />,
      },
      {
        value: "travel",
        label: "السفر",
        description: "أخطط للسفر إلى إسرائيل أو زيارتها",
        icon: <Plane className="h-6 w-6 text-teal-500" />,
      },
      {
        value: "personal_interest",
        label: "اهتمام شخصي",
        description: "مهتم باللغة والثقافة العبرية",
        icon: <Lightbulb className="h-6 w-6 text-yellow-500" />,
      },
      {
        value: "religion",
        label: "ديني",
        description: "لأغراض دينية أو روحية",
        icon: <BookOpen className="h-6 w-6 text-indigo-500" />,
      },
      {
        value: "other",
        label: "أخرى",
        description: "دافع آخر غير مذكور",
        icon: <Coffee className="h-6 w-6 text-orange-500" />,
      },
    ],
    type: "single",
  },
  {
    id: "goal",
    title: "ما هو هدفك الذي تريد تحقيقه مع اللغة العبرية؟",
    options: [
      {
        value: "basic_conversation",
        label: "المحادثة الأساسية",
        description: "القدرة على التحدث في المواقف اليومية",
        icon: <MessageCircle className="h-6 w-6 text-blue-500" />,
      },
      {
        value: "fluency",
        label: "الطلاقة",
        description: "التحدث بطلاقة كمتحدث أصلي تقريباً",
        icon: <Zap className="h-6 w-6 text-yellow-500" />,
      },
      {
        value: "reading_writing",
        label: "القراءة والكتابة",
        description: "فهم النصوص المكتوبة والقدرة على الكتابة",
        icon: <BookOpenIcon className="h-6 w-6 text-purple-500" />,
      },
      {
        value: "professional",
        label: "المهنية",
        description: "استخدام العبرية في بيئة العمل",
        icon: <Building2 className="h-6 w-6 text-green-500" />,
      },
      {
        value: "academic",
        label: "أكاديمية",
        description: "استخدام العبرية للدراسة أو البحث الأكاديمي",
        icon: <GraduationCapIcon className="h-6 w-6 text-red-500" />,
      },
      {
        value: "cultural",
        label: "ثقافية",
        description: "فهم الثقافة والأدب والإعلام العبري",
        icon: <Globe className="h-6 w-6 text-teal-500" />,
      },
    ],
    type: "single",
  },
  {
    id: "previous_methods",
    title: "ما هي الطرق التي جربتها للتعلم؟",
    options: [
      {
        value: "mobile_app",
        label: "تطبيق جوال",
        icon: <Smartphone className="h-6 w-6" />,
      },
      {
        value: "online_teacher",
        label: "معلم عبر الإنترنت",
        icon: <Laptop className="h-6 w-6" />,
      },
      {
        value: "school",
        label: "المدرسة",
        icon: <BookOpen className="h-6 w-6" />,
      },
      {
        value: "language_courses",
        label: "دورات اللغة",
        icon: <Building className="h-6 w-6" />,
      },
      {
        value: "youtube",
        label: "يوتيوب",
        icon: <Video className="h-6 w-6" />,
      },
    ],
    type: "multi",
  },
  {
    id: "feeling_confidence",
    title: "كيف تشعر عندما تحاول التحدث باللغة العبرية؟",
    options: [
      {
        value: "very_low",
        label: "منخفض جداً",
        description: "أشعر بالخجل الشديد وغير واثق على الإطلاق",
        icon: <ThumbsDown className="h-6 w-6 text-red-500" />,
      },
      {
        value: "low",
        label: "منخفض",
        description: "أشعر بعدم الارتياح ونقص الثقة معظم الوقت",
        icon: <Frown className="h-6 w-6 text-orange-500" />,
      },
      {
        value: "neutral",
        label: "محايد",
        description: "أشعر بالراحة في بعض المواقف وعدم الراحة في مواقف أخرى",
        icon: <Smile className="h-6 w-6 text-yellow-500" />,
      },
      {
        value: "confident",
        label: "واثق",
        description: "أشعر بالراحة نسبياً عند التحدث بالعبرية",
        icon: <ThumbsUp className="h-6 w-6 text-blue-500" />,
      },
      {
        value: "very_confident",
        label: "واثق جداً",
        description: "أشعر بالثقة التامة عند التحدث بالعبرية",
        icon: <Award className="h-6 w-6 text-green-500" />,
      },
    ],
    type: "single",
  },
  {
    id: "feeling_frustration",
    title: "ما مدى شعورك بالإحباط عندما تحاول التعلم أو التحدث بالعبرية؟",
    options: [
      {
        value: "not_at_all",
        label: "لا أشعر بالإحباط على الإطلاق",
        description: "عملية التعلم سهلة وممتعة بالنسبة لي",
        icon: <Smile className="h-6 w-6 text-green-500" />,
      },
      {
        value: "slightly",
        label: "أشعر بإحباط قليل",
        description: "أحيانًا أواجه بعض التحديات لكنها لا تزعجني كثيرًا",
        icon: <ThumbsUp className="h-6 w-6 text-blue-500" />,
      },
      {
        value: "moderately",
        label: "أشعر بإحباط متوسط",
        description: "أواجه صعوبات ومواقف محبطة بشكل متكرر",
        icon: <AlertCircle className="h-6 w-6 text-yellow-500" />,
      },
      {
        value: "very",
        label: "أشعر بإحباط كبير",
        description: "أشعر بالإحباط معظم الوقت عندما أحاول التحدث أو التعلم",
        icon: <Frown className="h-6 w-6 text-orange-500" />,
      },
      {
        value: "extremely",
        label: "أشعر بإحباط شديد جدًا",
        description:
          "أشعر بالعجز والإحباط الشديد في كل مرة أحاول فيها استخدام العبرية",
        icon: <XCircle className="h-6 w-6 text-red-500" />,
      },
    ],
    type: "single",
  },
  {
    id: "feeling_motivation",
    title: "كم أنت متحمس الآن لبدء رحلة تعلم العبرية معنا؟",
    options: [
      {
        value: "not_motivated",
        label: "غير متحمس",
        description: "أفتقد الدافع لمواصلة التعلم بسبب التجارب السابقة",
        icon: <Battery className="h-6 w-6 text-red-500" />,
      },
      {
        value: "slightly_motivated",
        label: "متحمس قليلاً",
        description: "لدي بعض الاهتمام ولكن ليس لدي حافز قوي",
        icon: <BatteryMedium className="h-6 w-6 text-orange-500" />,
      },
      {
        value: "moderately_motivated",
        label: "متحمس بشكل معتدل",
        description: "أنا مهتم بالتعلم ولكنني أحتاج إلى دفعة",
        icon: <BatteryCharging className="h-6 w-6 text-yellow-500" />,
      },
      {
        value: "highly_motivated",
        label: "متحمس جداً",
        description: "أنا مصمم على تعلم العبرية وتحسين مهاراتي",
        icon: <Zap className="h-6 w-6 text-blue-500" />,
      },
      {
        value: "extremely_motivated",
        label: "متحمس للغاية",
        description:
          "أنا شغوف وملتزم تماماً بإتقان اللغة العبرية مهما كلف الأمر",
        icon: <Flame className="h-6 w-6 text-green-600" />,
      },
    ],
    type: "single",
  },
];
